name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    # La parte de steps es nuestro pipeline, es decir la serie de pasos que va a seguir
    steps: 
    # Este paso toma todo el codigo del repo
    - name: checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Con esto hacemos un versionamiento "automatico" para evitar
    # hacerlo manual
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major"
        minor_pattern: "feat"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
    # El id nos ayuda a llamar a este paso en otros pasos
      id: version

        
    # Ahora vamos a tratar a acceder con nuestras credenciales a docker hub
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      # El simbolo de pipe | indica que se van a introducir comandos   
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Agregando nueva versión: $NEW_VERSION !!"
        echo "Fin del login"
        
    # Construccion de la imagen
    - name: build docker image
      run: |
        docker build -t angeloc19/docker-graphql:0.0.1 .
        docker build -t angeloc19/docker-graphql .

    # Hacer push a la imagen
    - name: push docker image
      run: |
        docker push angeloc19/docker-graphql:0.0.1
        docker push angeloc19/docker-graphql
        

    

        







    

    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
